### ISSUE TITLE
Could this be linked to from the website

### ISSUE THREAD

**Issue by rmcolq** [epi2me-labs/wf-template#2]
### Is your feature related to a problem?

I discovered this exists at ION BRU. I have recently been working on importing custom workflows of my own using the directions on this page https://labs.epi2me.io/nexflow-for-epi2melabs/ and didn't know this existed. 

### Describe the solution you'd like

Link to wf-template from the main how to page https://labs.epi2me.io/nexflow-for-epi2melabs/

### Describe alternatives you've considered

There was enough information on the page already for me to succeed in importing my existing nextflow pipeline in a minimal way, but I might have included more useful features...

**Comment by cjw85** [comment]
Hi Rachel,

This is a good idea. We'll add a link.
