### ISSUE TITLE
json schema specification

### ISSUE THREAD

**Issue by jfouret** [epi2me-labs/wf-template#3]
### Is your feature related to a problem?

Currently you all your workflow (like nf-core) uses the schema http://json-schema.org/draft-07/schema

However, another schema might be used in the future like the one implemented in the nf-schema plugin ( that replace nf-validation): https://json-schema.org/draft/2020-12/schema

This second schema is not recognized by the EPI2ME application.

### Describe the solution you'd like

- Indicate if and when the new schema will be supported by the EPI2ME plateform.
- Depending on that, with this template, make it clear if users shall not update the schema specs.

### Describe alternatives you've considered

- You might consider that the EPI2ME agent compatibility info shall not be of concern here, but as it is closed-source I did not find anything related to this

**Comment by SamStudio8** [comment]
We currently have no plans to adopt nf-schema at this time.
