### ISSUE TITLE
Unable to run/pull Nextflow wf-template via WSL2

### ISSUE THREAD

**Issue by mishkb** [epi2me-labs/wf-template#4]
### Operating System

Windows 11

### Other Linux

Ubuntu 22.04 via WSL2

### Workflow Version

v5.3.0

### Workflow Execution

Command line (Local)

### Other workflow execution

wf-template

### CLI command run

git clone https://github.com/epi2me-labs/wf-template.git
nextflow run epi2me-labs/wf-template

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

Hi,

I am trying to run epi2me via command line in WSL2 on a Windows 11 laptop. I have been following the install instructions here https://labs.epi2me.io/nextflow-on-windows/. 
After installing Docker Desktop (directly in Windows, then allowing WSL2) and Nextflow via WSL2 running Ubuntu 22.04 LTS - I have verified that Nextflow works, successfully running the `nextflow run blast-example -with-docker`  as per instructions [here ](https://www.nextflow.io/blog/2021/setup-nextflow-on-windows.html).

But I'm running into the following errors when I try to pull/run an epi2me workflow.

From git clone https://github.com/epi2me-labs/wf-template.git I get the following:
```
(base) xxxx@LAPTOP-YYYY:~$ git clone https://github.com/epi2me-labs/wf-template.git
Cloning into 'wf-template'...
fatal: unable to access 'https://github.com/epi2me-labs/wf-template.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
```

And from if I try to just run the wf-template via nextflow directly:
```
(base) xxxx@LAPTOP-YYYY:~$ nextflow run epi2me-labs/wf-template --help
curl: (35) error:0A000126:SSL routines::unexpected eof while reading

 N E X T F L O W   ~  version 24.04.4

Pulling epi2me-labs/wf-template ...
WARN: Cannot read project manifest -- Cause: Remote host terminated the handshake
Cannot find `epi2me-labs/wf-template` -- Make sure exists a GitHub repository at this address `https://github.com/epi2me-labs/wf-template`
```

FYI - same errors occur when trying to use wf-16S.
Any suggestions as to next steps to resolve?

### Relevant log output

```shell
(base) xxxx@LAPTOP-YYYY:~$ git clone https://github.com/epi2me-labs/wf-template.git
Cloning into 'wf-template'...
fatal: unable to access 'https://github.com/epi2me-labs/wf-template.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
(base) xxxx@LAPTOP-YYYY:~$ nextflow run epi2me-labs/wf-template --help

 N E X T F L O W   ~  version 24.04.4

Pulling epi2me-labs/wf-template ...
WARN: Cannot read project manifest -- Cause: Remote host terminated the handshake
Cannot find `epi2me-labs/wf-template` -- Make sure exists a GitHub repository at this address `https://github.com/epi2me-labs/wf-template`
(base) xxxx@LAPTOP-YYYY:~$ nextflow pull epi2me-labs/wf-template
Checking epi2me-labs/wf-template ...
WARN: Cannot read project manifest -- Cause: Remote host terminated the handshake
Cannot find `epi2me-labs/wf-template` -- Make sure exists a GitHub repository at this address `https://github.com/epi2me-labs/wf-template`
```

### Were you able to successfully run the latest version of the workflow with the demo data?

no

**Comment by nrhorner** [comment]
Hi @mishkb This appears to be a problem with `git` and not the EPI2ME workflows. This might be of some help: https://stackoverflow.com/a/60292604

**Comment by mishkb** [comment]
Thanks @nrhorner - I'll check this out and report back is it resolves the issue.

**Comment by SamStudio8** [comment]
Closing stale issue - please get back to us if there is still a problem.
